// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title StreetMobilizationRegistry
 * @dev A production-ready registry for managing street children identities securely.
 * It combines biometric uniqueness with blockchain immutability to prevent trafficking and fraud.
 */
contract StreetMobilizationRegistry {
    
    // --- Data Structures ---

    struct ChildRecord {
        string childId;          // Unique ID generated by the system (e.g., SM-KE-2026-001)
        bytes32 biometricHash;   // Cryptographic hash of biometric data (fingerprint/iris)
        bytes32 dataHash;        // Hash of off-chain data (IPFS CID or database pointer)
        uint256 timestamp;       // Block timestamp of registration
        address registrar;       // Address of the authorized entity that performed registration
        bool active;             // Status of the record
    }

    // --- State Variables ---

    address public owner;
    
    // Mapping from childId to the full record
    mapping(string => ChildRecord) private records;
    
    // Mapping from biometricHash to childId to ensure uniqueness and allow lookups
    mapping(bytes32 => string) private biometricToId;

    // Mapping to track if a biometric hash has already been registered
    mapping(bytes32 => bool) public biometricExists;

    // Authorized registrars (NGOs, Government agencies, Shelters)
    mapping(address => bool) public isAuthorizedRegistrar;

    // --- Events ---

    /**
     * @dev Audit Trail Events
     * Every critical operation emits an event to ensure full transparency and accountability.
     */
    event ChildRegistered(string indexed childId, bytes32 indexed biometricHash, address indexed registrar, uint256 timestamp);
    event ChildRecordUpdated(string indexed childId, address indexed actor, uint256 timestamp);
    event BiometricVerified(string indexed childId, address indexed verifier, uint256 timestamp);
    event DataHashUpdated(string indexed childId, bytes32 newDataHash, address indexed actor, uint256 timestamp);
    
    event RegistrarAuthorized(address indexed registrar);
    event RegistrarDeauthorized(address indexed registrar);

    // --- Modifiers ---

    modifier onlyOwner() {
        require(msg.sender == owner, "Only owner can perform this action");
        _;
    }

    modifier onlyAuthorized() {
        require(isAuthorizedRegistrar[msg.sender] || msg.sender == owner, "Not authorized to register/update");
        _;
    }

    // --- Constructor ---

    constructor() {
        owner = msg.sender;
        isAuthorizedRegistrar[msg.sender] = true; // Owner is authorized by default
    }

    // --- Administrative Functions ---

    /**
     * @dev Authorize an address to register and update child records.
     * @param registrar Address of the NGO or Government agency.
     */
    function authorizeRegistrar(address registrar) external onlyOwner {
        isAuthorizedRegistrar[registrar] = true;
        emit RegistrarAuthorized(registrar);
    }

    /**
     * @dev Deauthorize an address.
     * @param registrar Address to be removed.
     */
    function deauthorizeRegistrar(address registrar) external onlyOwner {
        isAuthorizedRegistrar[registrar] = false;
        emit RegistrarDeauthorized(registrar);
    }

    // --- Core Functions ---

    /**
     * @notice Registers a new child identity on the blockchain.
     * @dev Prevents duplicate biometric entries to stop identity fraud.
     * @param _childId Unique identifier for the child.
     * @param _biometricHash Hash of the child's biometric data.
     * @param _dataHash Hash referencing off-chain metadata (IPFS/Database).
     */
    function registerChild(
        string calldata _childId,
        bytes32 _biometricHash,
        bytes32 _dataHash
    ) external onlyAuthorized {
        // Validation
        require(bytes(_childId).length > 0, "Child ID cannot be empty");
        require(_biometricHash != bytes32(0), "Biometric hash required");
        require(_dataHash != bytes32(0), "Data hash required");
        
        // Ensure biometric uniqueness (Crucial for preventing trafficking/duplicate IDs)
        require(!biometricExists[_biometricHash], "StreetRegistry: Biometric data already registered");
        
        // Ensure childId uniqueness
        require(bytes(records[_childId].childId).length == 0, "StreetRegistry: Child ID already exists");

        // Store the record
        records[_childId] = ChildRecord({
            childId: _childId,
            biometricHash: _biometricHash,
            dataHash: _dataHash,
            timestamp: block.timestamp,
            registrar: msg.sender,
            active: true
        });

        // Map biometric to ID for verification lookups and uniqueness tracking
        biometricToId[_biometricHash] = _childId;
        biometricExists[_biometricHash] = true;

        emit ChildRegistered(_childId, _biometricHash, msg.sender, block.timestamp);
    }

    /**
     * @notice Verifies a child's identity using their biometric hash.
     * @param _biometricHash The hash of the biometric data provided during identification.
     * @return childId The unique ID of the matched child.
     * @return record The full ChildRecord struct.
     */
    function verifyChild(bytes32 _biometricHash) external returns (string memory childId, ChildRecord memory record) {
        childId = biometricToId[_biometricHash];
        require(bytes(childId).length > 0, "No record found for this biometric");
        record = records[childId];
        
        emit BiometricVerified(childId, msg.sender, block.timestamp);
    }

    /**
     * @notice Updates the off-chain data reference for a child record.
     * @dev Used for tracking interventions, movement, or aid distributions.
     * @param _childId The unique ID of the child.
     * @param _newDataHash The new IPFS/Database pointer hash.
     */
    function updateDataHash(string calldata _childId, bytes32 _newDataHash) external onlyAuthorized {
        require(bytes(records[_childId].childId).length > 0, "Record does not exist");
        require(_newDataHash != bytes32(0), "New data hash required");

        records[_childId].dataHash = _newDataHash;
        
        emit DataHashUpdated(_childId, _newDataHash, msg.sender, block.timestamp);
        emit ChildRecordUpdated(_childId, msg.sender, block.timestamp);
    }

    /**
     * @notice Retrieves the full record of a child.
     * @param _childId The unique ID of the child.
     * @return The ChildRecord struct containing all metadata.
     */
    function getChildRecord(string calldata _childId) external view returns (ChildRecord memory) {
        require(bytes(records[_childId].childId).length > 0, "Record does not exist");
        return records[_childId];
    }

    /**
     * @dev Check if a biometric hash is already registered.
     */
    function isBiometricRegistered(bytes32 _biometricHash) external view returns (bool) {
        return biometricExists[_biometricHash];
    }
}
